# Generated by Django 6.0.6 on 2026-07-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitem',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
