# Generated by Django 6.0.6 on 2026-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normalize_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('distributor', 'Distributor')], default='distributor', max_length=50),
        ),
    ]
